config/routes.rb
Rails.application.routes.draw do

  root "artists#index"

  resources :albums
  resources :artists
  resources :orders

end

app/models/album.rb
class Album < ApplicationRecord
	belongs_to :artist
	belongs_to :order
	validates :title, presence: true
	validates :artist_id, presence: true
	validates :in_stock, presence: true
	validates :price, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :albums, dependent: :delete_all
	validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_one :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_select_collections, only: [:edit, :create, :new, :update]

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to @album
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to @album
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def album_params
      params.require(:album).permit(:title, :artist_id, :in_stock, :price)
    end

    def set_select_collections
      @artist_options = Artist.all.map{|a| [a.name, a.id]}
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

	def index
		@artists = Artist.all
	end

	def show
		@artist = Artist.find(params[:id])
	end

	def new
		@artist = Artist.new
	end

	def create
		@artist = Artist.new(artist_params)

		if @artist.save
			redirect_to @artist
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@artist = Artist.find(params[:id])
	end

	def update
		@artist = Artist.find(params[:id])

		if @artist.update(artist_params)
			redirect_to @artist
		else
			render :edit, status: :see_other
		end
	end

	def destroy
		@artist = Artist.find(params[:id])
		@artist.destroy

		redirect_to root_path, status: :see_other
	end

	private
		def artist_params
			params.require(:artist).permit(:name)
		end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def index
		@orders = Order.all
	end

	def show
		@orders = Order.find(params[:id])
	end

	def new
		@order = Order.new
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/albums/_form.html.erb
<%= form_with model: album do |form| %>
 	<div>
 		<%= form.select(:artist_id, @artist_options) %>
 		<% album.errors.full_messages_for(:artist_id).each do |message| %>
 			<div><%= message %></div>
 		<% end %>
 	</div>
 	<div>
 		<%= form.label :title %>
 		<br />
 		<%= form.text_field :title %>
 		<% album.errors.full_messages_for(:title).each do |message| %>
 			<div><%= message %></div>
 		<% end %>
 	</div>
    <div>
        <%= form.label :in_stock %>
        <br />
        <%= form.text_field :in_stock %>
        <% album.errors.full_messages_for(:in_stock).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :price %>
        <br />
        <%= form.text_field :price %>
        <% album.errors.full_messages_for(:price).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
 	<div>
 		<%= form.submit %>
 	</div>
 <% end %>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render "form", album: @album %>

app/views/albums/index.html.erb
<h1>Albums</h1>

<ul>
	<% @albums.each do |album| %>
		<li>
			<%= link_to album.title, album %>
		</li>
	<% end %>
</ul>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render "form", album: @album %>

app/views/albums/show.html.erb
<h1><%= @album.artist.name %> - <%= @album.title %></h1>

<p>Currently in stock: <%= @album.in_stock %></p>
<p>Price: <%= @album.price %></p>

<p><%= link_to "Artist's page", @album.artist %></p>
<p><%= link_to "Edit", edit_album_path(@album) %></p>
<p>
	<%= link_to "Destroy", album_path(@album), data: {
		turbo_method: :delete,
		turbo_confirm: "Are you sure ?"
	} %>
</p>

app/views/artists/_form.html.erb
<%= form_with model: artist do |form| %>
	<div>
		<%= form.label :name %>
		<br />
		<%= form.text_field :name %>
		<% artist.errors.full_messages_for(:name).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>
	<%= form.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form", artist: @artist %>

app/views/artists/index.html.erb
<h1>Artists</h1>

<ul>
	<% @artists.each do |artist| %>
		<li><%= link_to artist.name, artist %></li>
	<% end %>
</ul>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= form_with model: @artist do |form| %>
	<div>
		<%= form.label :name %>
		<br />
		<%= form.text_field :name %>
		<% @artist.errors.full_messages_for(:name).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>
	<%= form.submit %>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<% @artist.albums.each do |album| %>
	<p><%= link_to album.title, album %></p>
<% end %>

<p><%= link_to "Edit", edit_artist_path(@artist) %></p>
<p>
	<%= link_to "Destroy", artist_path(@artist), data: {
		turbo_method: :delete,
		turbo_confirm: "Are you sure ?"
	} %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StCk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h1>All orders</h1>

<% @orders.each do |order| %>
	<p><%= order.albums %></p>
<% end %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", albums: @albums %>

<script>

	$.('#AddAlbumField').add(function()
	{
		$.('#AlbumList').append('<%= form.select @albums %>');
	});

</script>